(function(global){
  'use strict';
  const W=global.WSXZ,F=global.Frontier,X=global.ClanExpansion,$=id=>document.getElementById(id),drafts=new Map();
  const baseRender=Experience.render,baseShell=Experience.shell,baseEnrich=Experience.enrich;
  let genealogyView='branches',familySearch='',treeScale=.65;
  const n=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
  function itemIcon(index,size=''){const icon=n('span','item-art '+size);icon.style.backgroundPosition=`${(index%4)*100/3}% ${Math.floor(index/4)*50}%`;icon.setAttribute('aria-hidden','true');return icon;}
  function title(name,caption){const h=n('div','window-heading');h.append(n('h2','',name));if(caption)h.append(n('span','',caption));return h;}
  function frame(name,caption){const e=n('article','game-window');e.append(title(name,caption));return e;}
  function selectPeople(e,key,filter=()=>true){const sel=n('select','agent-select');sel.setAttribute('aria-label',(F.goods.find(g=>g.id===key)?.name||F.sites.find(s=>s.id===key)?.name||'派遣')+'选择族人');const blank=n('option','','选择族人');blank.value='';sel.append(blank);for(const c of e.world.residents().filter(filter)){const op=n('option','',c.name+' · '+W.realmLabel(c));op.value=c.id;sel.append(op);}sel.value=drafts.get(key)||'';sel.onchange=()=>drafts.set(key,sel.value);return sel;}
  function scene(e,b,portrait){const s=e.state,f=F.ensure(s),wrap=n('section','game-scene');const img=n('img','scene-background');img.src='art/v2/sanctuary.webp';img.alt='可交互的家族山门';wrap.append(img);wrap.dataset.season=Math.floor(W.absoluteMonth(s)/3)%4;
    const mist=n('div','scene-mist');mist.setAttribute('aria-hidden','true');wrap.append(mist);for(let i=0;i<12;i++){const mote=n('i','spirit-mote');mote.style.left=(7+i*31%89)+'%';mote.style.top=(15+i*19%75)+'%';mote.style.animationDelay=(-i*1.8)+'s';wrap.append(mote);}
    const plaque=n('div','clan-plaque');plaque.append(n('small','','云州 · 本家山门'),n('h2','',s.playerFamily.name),n('span','',Dname(s.playerFamily.rank)+' · '+W.spiritVein(s.playerFamily.spiritVeinTier)));wrap.append(plaque);
    const pins=[['议事堂','策',59,31,'panel:policies'],['藏经阁','经',85,41,'tab:传承'],['药圃','药',17,66,'tab:经营'],['演武场','武',60,69,'panel:buildings'],['祖祠','祠',35,36,'panel:ancestral'],['山门','门',37,61,'panel:positions']];for(const[name,glyph,x,y,id]of pins){const pin=b('',id);pin.className='building-node';pin.style.left=x+'%';pin.style.top=y+'%';const key=({'议事堂':'hall','藏经阁':'library','药圃':'field','演武场':'trainingGround','祖祠':'ancestralHall','山门':'hall'})[name],level=s.alpha.buildings[key];pin.classList.add('level-'+level);pin.setAttribute('aria-label',name+' · '+level+'级');pin.append(n('span','building-glyph',glyph),n('span','building-label',name+' · '+level+'级'));wrap.append(pin);}
    const clanHUD=n('div','scene-clan-hud'),leader=W.findCharacter(s,s.playerFamily.leaderId);if(leader){portrait(clanHUD,leader.id);const detail=n('div');detail.append(n('strong','',leader.name),n('small','',W.realmLabel(leader)+' · '+leader.age+'岁'));clanHUD.append(detail,b('生平','select:'+leader.id));}wrap.append(clanHUD);
    const active=n('div','scene-activity');active.append(n('span','activity-dot'),n('span','',s.settings.timeSpeed==='paused'?'山门安宁 · 岁月暂歇':'灵气流转 · 修行进行中'));if(s.pendingDecisions.length)active.append(b('族务待议 '+s.pendingDecisions.length,'tab:大事'));active.append(b('推进一季','advance_quarter'));wrap.append(active);
    const rail=n('div','scene-action-rail');for(const[label,icon,id]of [['坊市',11,'tab:坊市'],['行囊',7,'tab:行囊'],['传承',2,'tab:传承'],['派遣',5,'tab:经营'],['族谱',10,'tab:族谱'],['山河',3,'tab:世界']]){const bt=b('',id);bt.className='scene-command';bt.append(itemIcon(icon),n('span','',label));rail.append(bt);}wrap.append(rail);
    const ticker=n('div','clan-ticker');const latest=s.history.at(-1);ticker.append(n('span','','族闻'),n('p','',latest?W.calendar(latest.year,latest.month)+' '+latest.text:'传承自今日开始。'),b('阅史','tab:大事'));wrap.append(ticker);return wrap;}
  function Dname(rank){return W.ALPHA_CONFIG.familyRanks[rank].name;}
  function shop(e,b){const f=F.ensure(e.state),wrap=frame(f.region==='xuantian'&&f.unlocked?'玄天坊市':'天河坊市','灵石换资粮 · 库存每年更新');wrap.classList.add('full-width');const nav=n('div','market-categories');for(const kind of ['全部','丹药','法器','材料','传承','补给']){const bt=b(kind,'market_filter:'+kind);if((drafts.get('marketFilter')||'全部')===kind)bt.classList.add('active');nav.append(bt);}wrap.append(nav);const grid=n('div','shop-grid'),category=drafts.get('marketFilter')||'全部';for(const g of F.goods.filter(g=>category==='全部'||g.kind===category)){const tile=n('article','shop-item'),locked=g.min>=4&&!f.unlocked||g.min>0&&!F.hasRealm(e,g.min),cost=g.id==='foundationPill'?e.state.alpha.market.price:g.price;const top=n('div','shop-item-top');top.append(itemIcon(g.icon),n('div','item-heading',g.name));tile.append(top,n('span','rarity rarity-'+g.min,g.kind+(g.min>=4?' · 玄天珍品':'')),n('p','item-description',g.description),n('small','stock-line','库存 '+f.stocks[g.id]+' · '+cost.toLocaleString()+' 灵石'));if(locked)tile.append(n('p','locked-copy',g.min>=4&&!f.unlocked?'需要开启玄天界': '需要本家'+W.label(F.order[g.min])+'修士'));const bt=b(locked?'尚未开放':'购入一份','shopbuy:'+g.id+':1');bt.disabled=locked||f.stocks[g.id]<1||e.state.playerFamily.spiritStones<cost;tile.append(bt);grid.append(tile);}wrap.append(grid);const sell=n('div','sell-counter');sell.append(n('h3','','材料收购'),n('p','','药材每份3灵石，灵材每份8灵石。把多余资粮换为经营资金。'));for(const[k,name]of [['herbs','药材'],['materials','灵材']])for(const count of [10,50]){const bt=b('出售'+count+name,'shopsell:'+k+':'+count);bt.disabled=e.state.alpha[k]<count;sell.append(bt);}wrap.append(sell,b('查看行囊与装备','tab:行囊'));return wrap;}
  function bag(e,b,portrait){const f=F.ensure(e.state),wrap=frame('仙族行囊','物品归族库 · 法器归族人');wrap.classList.add('full-width');const grid=n('div','bag-grid');for(const g of F.goods){const count=F.inventory(e,g.id);if(!count)continue;const tile=n('article','bag-item');tile.append(itemIcon(g.icon),n('h3','',g.name),n('strong','bag-count','×'+count),n('p','item-description',g.description));if(['healing','manual','sword','ring','talisman'].includes(g.id)){const sel=selectPeople(e,g.id,c=>g.id==='healing'?['light','severe'].includes(c.health)&&c.injuryMonths>0:g.id==='manual'?(f.manualUses[c.id]||0)<5&&c.comprehension<100:c.cultivationStarted&&!X.busy(e.state,c.id));tile.append(sel);const bt=b(['sword','ring','talisman'].includes(g.id)?'装备法器':'使用物品','baguse:'+g.id);bt.disabled=!sel.value;sel.addEventListener('change',()=>bt.disabled=!sel.value);tile.append(bt);}grid.append(tile);}if(!grid.children.length)grid.append(n('p','empty-state','族库尚无物品。去坊市购入丹药、法器与补给，为下一次远行做准备。'));wrap.append(grid);const gears=n('div','equipped-roster');gears.append(n('h3','','族人法器'));for(const[id,key]of Object.entries(f.equipment)){const c=W.findCharacter(e.state,id);if(!c||c.lifeStatus!=='alive')continue;const row=n('div','equipped-person');portrait(row,id);row.append(n('span','',c.name),itemIcon(F.goods.find(g=>g.id===key).icon,'small'),n('strong','',F.goods.find(g=>g.id===key).name),b('卸下法器','bagunequip:'+id));gears.append(row);}wrap.append(gears,b('前往坊市','tab:坊市'));return wrap;}
  function world(e,b){const f=F.ensure(e.state),wrap=frame('两界山河',f.region==='xuantian'?'玄天界 · 化神与炼虚道途':'云州 · 仙族起源');wrap.classList.add('full-width');const regions=n('div','region-switch');regions.append(b('云州','region:yunzhou'),b('玄天界'+(!f.unlocked?' · 未开辟':''),'region:xuantian'));wrap.append(regions);if(f.region==='yunzhou'){const map=n('div','atlas-map');const img=n('img');img.src='art/world_map_yunzhou.png';img.alt='云州势力地图';map.append(img);const coords=[[18,28],[45,27],[76,25],[33,50],[64,46],[82,55],[18,66],[42,73],[69,80],[88,73],[23,14],[61,14]];e.state.alpha.world.forEach((clan,i)=>{const bt=b(clan.name,'faction:'+clan.id);bt.className='atlas-node';bt.style.left=coords[i][0]+'%';bt.style.top=coords[i][1]+'%';map.append(bt);});const market=b('天河坊市','tab:坊市');market.className='atlas-node market-node';market.style.left='65%';market.style.top='58%';map.append(market);wrap.append(map);const locations=n('div','region-locations');for(const l of W.ALPHA_CONFIG.exploration){const bt=b(l.name+' · '+e.world.expeditionAccess(l.id).reason,'explore:'+l.id);locations.append(bt);}wrap.append(locations);return wrap;}
    const map=n('div','atlas-map frontier-map');const img=n('img');img.src='art/v3/frontier.webp';img.alt='玄天界：瑶池药圃、霜天灵矿、太初道宫与归墟裂隙';map.append(img);for(const site of F.sites){const bt=b(site.name,'frontier_site:'+site.id);bt.className='atlas-node';bt.style.left=site.x+'%';bt.style.top=site.y+'%';if(!f.unlocked)bt.classList.add('sealed');map.append(bt);}wrap.append(map);if(!f.unlocked){const gate=n('div','gate-requirements');gate.append(n('h3','','破界而行'),n('p','','本家出现元婴修士后，可耗5000灵石、200灵材开辟界门。开启新的远行、珍材、高阶丹药和突破环境。'));const bt=b('开辟玄天界门','frontier_open');bt.disabled=!F.hasRealm(e,4)||e.state.playerFamily.spiritStones<5000||e.state.alpha.materials<200;gate.append(bt);wrap.append(gate);}else{const recipes=n('div','alchemy-table');recipes.append(n('h3','','玄天炼丹台'),n('p','','化神丹：玄灵莲2、药材800、灵材300、灵石2000\n炼虚丹：玄灵莲6、药材1800、灵材900、灵石6000'));recipes.append(b('炼制化神丹','alchemy:spiritPill'),b('炼制炼虚丹','alchemy:voidPill'),b('玄天坊市','tab:坊市'));wrap.append(recipes);}for(const j of f.journeys){const row=n('div','journey-progress');row.append(n('strong','',F.sites.find(x=>x.id===j.site).name),n('span','',(W.findCharacter(e.state,j.agent)?.name||'族人')+' · 剩余'+Math.max(0,j.ends-W.absoluteMonth(e.state))+'个月'));wrap.append(row);}return wrap;}
  function siteWindow(e,id,b){const site=F.sites.find(x=>x.id===id);if(!site)return frame('地点不存在');const wrap=frame(site.name,W.label(F.order[site.min])+'以上 · '+site.months+'个月');wrap.append(n('p','',site.description),n('p','',X.rewardText(site.reward)+' · 玄灵莲 +'+site.lotus),n('p','', '出行费用 '+site.cost+' 灵石 · 基础受伤概率 '+Math.round(site.risk*100)+'%，福缘可降低风险。'));wrap.append(selectPeople(e,site.id,c=>F.order.indexOf(c.realm)>=site.min&&c.health==='healthy'&&!c.isInRetreat&&!X.busy(e.state,c.id)));const bt=b('派遣远行','journey:'+site.id);bt.disabled=!F.ensure(e.state).unlocked;wrap.append(bt,b('返回山河','close'));return wrap;}
  function genealogy(e,b,portrait){const s=e.state,wrap=frame('血脉长卷','分支浏览 · 搜索定位 · 关系图缩放');wrap.classList.add('full-width','genealogy-window');const controls=n('div','genealogy-toolbar');controls.append(b('分支族谱','genealogy_view:branches'),b('关系全图','genealogy_view:graph'));const search=n('input');search.placeholder='搜索姓名，定位族谱';search.setAttribute('aria-label','搜索族谱');search.value=familySearch;search.oninput=()=>familySearch=search.value;const find=b('定位','genealogy_search');controls.append(search,find);wrap.append(controls);
    const people=W.allCharacters(s).filter(c=>(!c.factionId||c.factionId===s.playerFamily.id)&&(!familySearch||c.name.includes(familySearch))),focus=W.findCharacter(s,e._genealogyFocus||s.playerFamily.ancestorId);if(genealogyView==='graph'){const zoom=n('div','tree-tools');zoom.append(b('缩小','genealogy_zoom:-'),b('放大','genealogy_zoom:+'),b('适应屏幕','genealogy_fit'));wrap.append(zoom);const viewport=n('div','lineage-viewport'),canvas=n('div','lineage-canvas');const generations=[...new Set(people.map(c=>c.generation))].sort((a,b)=>a-b),group=generations.map(g=>people.filter(c=>c.generation===g));const width=Math.max(700,...group.map(p=>p.length*142)),height=generations.length*160+50;canvas.style.width=width*treeScale+'px';canvas.style.height=height*treeScale+'px';const inner=n('div','lineage-inner');inner.style.width=width+'px';inner.style.height=height+'px';inner.style.transform='scale('+treeScale+')';const points=new Map();for(const [gi,list]of group.entries())for(const [i,c]of list.entries())points.set(c.id,{x:(width-list.length*142)/2+i*142+71,y:gi*160+65});const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width',width);svg.setAttribute('height',height);svg.classList.add('lineage-edges');for(const c of people){const point=points.get(c.id);if(c.fatherId&&points.has(c.fatherId)){const parent=points.get(c.fatherId),path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',`M${parent.x},${parent.y+42} V${(parent.y+point.y)/2} H${point.x} V${point.y-43}`);svg.append(path);}}additionalEdges(people,points,svg);inner.append(svg);for(const c of people){const point=points.get(c.id),bt=personTile(e,c,b,portrait,'genealogy_focus:');bt.classList.add('graph-person');bt.style.left=point.x-61+'px';bt.style.top=point.y-43+'px';inner.append(bt);}canvas.append(inner);viewport.append(canvas);wrap.append(viewport,n("p","lineage-legend","实线为父系、虚线为母系，金色连线表示道侣。点击人物可以继续查看亲缘。"));let dragging=false,startX=0,startY=0,left=0,top=0;viewport.onpointerdown=ev=>{if(ev.target.closest('button'))return;dragging=true;startX=ev.clientX;startY=ev.clientY;left=viewport.scrollLeft;top=viewport.scrollTop;viewport.setPointerCapture(ev.pointerId);};viewport.onpointermove=ev=>{if(dragging){viewport.scrollLeft=left-(ev.clientX-startX);viewport.scrollTop=top-(ev.clientY-startY);}};viewport.onpointerup=()=>dragging=false;
    }else{const branches=n('div','branch-list');for(const generation of [...new Set(people.map(c=>c.generation))].sort((a,b)=>a-b)){const row=n('section','generation-row');row.append(n('h3','', '第 '+generation+' 代'));const nodes=n('div','generation-members');for(const c of people.filter(c=>c.generation===generation))nodes.append(personTile(e,c,b,portrait,'genealogy_focus:'));row.append(nodes);branches.append(row);}if(!people.length)branches.append(n('p','empty-state','没有匹配的族人，请修改搜索。'));wrap.append(branches);}
    if(focus){const detail=n('section','genealogy-detail');detail.append(n('h3','',focus.name+' · 亲缘关系'));const relations=[['父亲',focus.fatherId],['母亲',focus.motherId],...focus.spouseIds.map(id=>['道侣',id]),...focus.childrenIds.map(id=>['子女',id])];for(const[label,id]of relations){const c=W.findCharacter(s,id);if(c)detail.append(b(label+' · '+c.name,'genealogy_focus:'+id));}detail.append(b('查看人物生平','select:'+focus.id));wrap.append(detail);}return wrap;}
  function personTile(e,c,b,portrait,prefix){const bt=b('',prefix+c.id);bt.className='lineage-person'+(c.lifeStatus==='dead'?' departed':'');portrait(bt,c.id);const desc=n('div');desc.append(n('strong','',c.name),n('small','',W.realmLabel(c)+' · '+(c.lifeStatus==='dead'?'已故':c.age+'岁')));bt.append(desc);if(e._genealogyFocus===c.id){bt.classList.add('focused');bt.setAttribute('aria-pressed','true');}return bt;}
  function additionalEdges(people,points,svg){const seen=new Set();for(const c of people){const p=points.get(c.id);if(c.motherId&&points.has(c.motherId)){const parent=points.get(c.motherId),path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',`M${parent.x+8},${parent.y+42} V${(parent.y+p.y)/2+7} H${p.x+8} V${p.y-43}`);path.classList.add('maternal-edge');svg.append(path);}for(const id of c.spouseIds){if(!points.has(id))continue;const pair=[c.id,id].sort().join(':');if(seen.has(pair))continue;seen.add(pair);const q=points.get(id),path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',`M${p.x},${p.y+34} L${q.x},${q.y+34}`);path.classList.add('spouse-edge');svg.append(path);}}}
  function studies(e,b){const x=X.ensure(e.state),wrap=frame('一族道藏','功法与经营 · 永久传承');wrap.classList.add('full-width','legacy-window');const tree=n('div','legacy-tree');const names={breath:0,herbal:1,commerce:2,meridian:3,formation:4,legacy:5};for(const t of X.studies){const done=x.studies.includes(t.id),locked=t.requires&&!x.studies.includes(t.requires),active=x.research?.id===t.id;const bt=b('','study:'+t.id);bt.className='legacy-node legacy-'+t.id+(done?' mastered':'')+(active?' researching':'')+(locked?' locked':'');bt.disabled=done||locked||!!x.research||e.state.playerFamily.spiritStones<t.cost||e.state.alpha.herbs<t.herbs;bt.append(itemIcon([2,10,11,5,7,6][names[t.id]]),n('strong','',t.name),n('span','',t.effect),n('small','',t.cost+'灵石'+(t.herbs?' · '+t.herbs+'药材':'')+' · '+t.months+'个月'),n('em','',done?'已掌握':active?'研习中 · 剩余'+Math.max(0,x.research.ends-W.absoluteMonth(e.state))+'月':locked?'前置：'+X.studies.find(s=>s.id===t.requires).name:x.research?'藏经阁忙碌':'研习此传承'));tree.append(bt);}wrap.append(tree,n('p','legacy-note','同一时刻只可研习一项。修炼加成乘算，经营加成每年兑现，已掌握的传承随存档长久保留。'));return wrap;}
  function render(p,card,b,portrait){const e=p.engine;if(p.ui.modal?.startsWith('frontier_site:')){$('content').append(siteWindow(e,p.ui.modal.split(':')[1],b));return true;}if(e&&!p.ui.modal&&e.state.meta.started){const root=$('content');if(p.ui.tab==='家族'){root.append(scene(e,b,portrait));return true;}if(p.ui.tab==='坊市'||p.ui.modal==='market'){root.append(shop(e,b));return true;}if(p.ui.tab==='行囊'){root.append(bag(e,b,portrait));return true;}if(p.ui.tab==='世界'){root.append(world(e,b));return true;}if(p.ui.tab==='族谱'){root.append(genealogy(e,b,portrait));return true;}if(p.ui.tab==='传承'){root.append(studies(e,b));return true;}}if(e&&p.ui.modal==='market'){$('content').append(shop(e,b));return true;}return baseRender(p,card,b,portrait);}
  function action(p,id){const e=p.engine;if(id.startsWith('market_filter:')){drafts.set('marketFilter',id.split(':')[1]);return true;}if(id.startsWith('frontier_site:')){p.ui.modal=id;return true;}if(id.startsWith('genealogy_view:')){genealogyView=id.split(':')[1];return true;}if(id==='genealogy_search'){const found=W.allCharacters(e.state).find(c=>(!c.factionId||c.factionId===e.state.playerFamily.id)&&c.name.includes(familySearch));if(found){e._genealogyFocus=found.id;p.ui.selectedId=found.id;}return true;}if(id.startsWith('genealogy_focus:')){e._genealogyFocus=id.split(':')[1];p.ui.selectedId=e._genealogyFocus;familySearch='';return true;}if(id.startsWith('genealogy_zoom:')){treeScale=Math.min(1.2,Math.max(.25,treeScale+(id.endsWith('+')?.1:-.1)));return true;}if(id==='genealogy_fit'){const people=W.allCharacters(e.state).filter(c=>!c.factionId||c.factionId===e.state.playerFamily.id),max=Math.max(1,...people.map(c=>people.filter(p=>p.generation===c.generation).length));treeScale=Math.min(.85,Math.max(.25,($('content').clientWidth-40)/Math.max(700,max*142)));return true;}return false;}
  function shell(p,b,portrait){baseShell(p,b,portrait);if(p.engine){document.body.dataset.region=F.ensure(p.engine.state).region;const heading=$('page-heading').querySelector('.section-title');if(heading&&p.ui.tab==='世界'&&!p.ui.modal){heading.querySelector('h2').textContent=F.ensure(p.engine.state).region==='xuantian'?'玄天山河':'云州山河';const sub=heading.querySelector('p');if(sub)sub.textContent=F.ensure(p.engine.state).region==='xuantian'?'破界而行，续写化神与炼虚道途。':'十族两宗门，山外觅仙缘。';}if(heading&&['坊市','行囊'].includes(p.ui.tab)&&!p.ui.modal){heading.querySelector('h2').textContent=p.ui.tab==='坊市'?(F.ensure(p.engine.state).region==='xuantian'&&F.ensure(p.engine.state).unlocked?'玄天坊市':'天河坊市'):'仙族行囊';const copy=heading.querySelector('p');if(copy)copy.textContent=p.ui.tab==='坊市'?'丹药、法器、珍材，皆为传承所用。':'为族人整装，为下一次远行做准备。';}}}
  function enrich(div,row,p,b){baseEnrich(div,row,p,b);if(p.engine&&row.portraitId){const gear=F.ensure(p.engine.state).equipment[row.portraitId];if(gear){const badge=n('div','gear-badge');badge.append(itemIcon(F.goods.find(g=>g.id===gear).icon,'small'),n('span','',F.goods.find(g=>g.id===gear).name));div.append(badge);}}
    if(p.engine&&p.ui.modal?.startsWith('decision:')){const d=p.engine.state.pendingDecisions.find(d=>'decision:'+d.id===p.ui.modal);if(d?.type==='major_breakthrough'&&['spirit','void'].includes(d.payload.target)){const pill=d.payload.target==='spirit'?'spiritPill':'voidPill';const bt=b('服'+F.goods.find(g=>g.id===pill).name+'突破（+12%）','resolve:'+d.id+':attempt:pill');bt.disabled=!F.inventory(p.engine,pill);div.append(bt);}}
    if(p.engine&&p.ui.modal?.startsWith('decision:')){const d=p.engine.state.pendingDecisions.find(d=>'decision:'+d.id===p.ui.modal);if(d?.type==='rank'){div.append(b('暂缓晋阶','postpone:'+d.id));if(!p.engine.world.rankEligible()){const copy=div.querySelector('p');if(copy)copy.textContent='晋阶条件已发生变化，需要重新准备。可选择暂缓，继续积累人口、资产与资粮。';}}if(d?.type==='event')div.append(b('延后一年','postpone:'+d.id));}
  }
  Experience.render=render;Experience.shell=shell;Experience.enrich=enrich;
  const modalWithViews=modal;modal=function(p,card,b){if(p.ui.modal==='quick_menu'){const menu=frame('族务入口','掌族、养人、承道、行商');const actions=n('div','quick-menu-grid');for(const[label,icon,id]of [['山门经营',5,'tab:经营'],['传承道藏',2,'tab:传承'],['天河坊市',11,'tab:坊市'],['仙族行囊',7,'tab:行囊'],['岁月大事',10,'tab:大事'],['全局设置',3,'menu']]){const bt=b('',id);bt.append(itemIcon(icon),n('span','',label));actions.append(bt);}menu.append(actions,b('返回山门','close'));return[menu];}return modalWithViews(p,card,b);};
  const actionWithViews=action;action=function(p,id){if(id==='quick_menu'){p.ui.modal='quick_menu';return true;}return actionWithViews(p,id);};
  const baseNavIcon=Experience.navIcon;Experience.navIcon=tab=>{if(!['坊市','行囊','更多'].includes(tab))return baseNavIcon(tab);const icon=n('span','line-icon');icon.setAttribute('aria-hidden','true');const path=tab==='更多'?'M4 6h16M4 12h16M4 18h16':tab==='坊市'?'M3 9h18L19 3H5L3 9M4 9v12h16V9M9 21v-7h6v7M2 9v3h20V9':'M7 7 5 3h14l-2 4M7 7c-5 4-7 12-2 14h14c5-2 3-10-2-14H7M7 7h10M12 12v6M10 13h4';icon.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.35" stroke-linecap="round" stroke-linejoin="round"><path d="'+path+'"/></svg>';return icon;};
  function modal(p,card,b){if(p.ui.modal?.startsWith('frontier_site:'))return[siteWindow(p.engine,p.ui.modal.split(':')[1],b)];if(p.ui.modal==='market')return[shop(p.engine,b)];if(p.ui.modal==='guide'){const help=frame('掌族手册','山门沙盘 · 六境传承');help.append(n('p','','时间与弹窗：通知不会自动消失，必须确认；所有窗口打开时暂停岁月。待决事件需要同意、拒绝或暂缓，才能继续。'),n('p','','坊市：丹药用于破境，回春露治疗伤势，残卷提升悟性，法器可装备。灵材、药材直接入库；锦囊在下一次派遣时消耗。'),n('p','','族谱：分支视图按代纵向排列，不必横拉。点击人物看亲缘；关系全图支持缩放、适应屏幕和按住空白拖动。'),n('p','','元婴之后：元婴可开辟玄天界，采集玄灵莲、炼丹、培养化神与炼虚修士。大境界需要对应灵脉、藏经阁与资源。'),n('p','','传承与经营：保留六项研习。给族人装备法器、准备补给，再派遣委托，形成积累资源与培养后辈的循环。'),b('已阅手册','close'));return[help];}return p.rows().map(row=>card({...row,fullscreen:false}));}
  function surnameForm(p,wrap){const form=n('div','surname-form'),label=n('label','','家族姓氏'),input=n('input');input.id='clan-surname';input.maxLength=8;input.autocomplete='off';input.placeholder='输入姓氏，如林、苏、欧阳';input.value=p.pendingSurname||'';label.htmlFor=input.id;const preview=n('p','surname-preview'),choices=n('div','surname-choices');choices.setAttribute('aria-label','常用姓氏');const update=()=>{p.pendingSurname=input.value;$('surname').value=input.value;const value=input.value.trim();preview.textContent=value?value+'氏 · 一脉传承，自此开篇。':'请输入1至8字姓氏，也支持复姓。';for(const bt of wrap.querySelectorAll('[data-action="clan_generate"],[data-action="new_backup"],[data-action="new_overwrite"]'))bt.disabled=!value||value.length>8;};input.oninput=update;for(const surname of ['林','苏','陈','李','叶','萧','沈','顾','陆','肖','欧阳','慕容']){const bt=n('button','',surname);bt.type='button';bt.onclick=()=>{input.value=surname;update();input.focus();};choices.append(bt);}form.append(label,input,choices,preview);wrap.insertBefore(form,wrap.firstChild?.nextSibling||null);update();}
  const modalWithSurname=modal;modal=function(p,card,b){if(p.ui.modal==='clan_setup'){const setup=frame('择姓立族','第一步 · 为家族落下名字');setup.append(n('p','','先选择或输入姓氏，再生成初始族人。生成后仍需确认开局。'),b('生成初始家族','clan_generate'),b('取消','close'));surnameForm(p,setup);return[setup];}const views=modalWithSurname(p,card,b);if(p.ui.modal==='new_confirm'&&views[0])surnameForm(p,views[0]);return views;};
  global.MatureUI={action,agent:id=>drafts.get(id),itemIcon,render,frame,modal};
})(window);
