const assert=require('node:assert/strict');
const W=require('../core.js');
const X=require('../expansion.js');
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
function game(seed='expansion-qa'){const saves=new W.SaveSystem(new W.MemoryStorage());const e=W.Engine.create('肖',seed,0,Date.now(),saves);X.attach(e);e.start();return e;}
function advance(e,n){for(let i=0;i<n;i++)e.time.tick();}
test('旧版存档迁移后初始化经营系统',()=>{const e=game();delete e.state.expansion;const s=e.saves.decode(e.saves.export(e.state));assert.equal(s.expansion,undefined);const next=new W.Engine(s,e.saves);X.attach(next);assert.equal(next.state.expansion.version,2);W.validateState(next.state);});
test('开局生成春季抉择并保存',()=>{const e=game();assert.equal(e.state.expansion.seasonEvent.index,0);assert.equal(e.saves.load().expansion.seasonEvent.index,0);});
test('采药扣费、占用人手与三月结算',()=>{const e=game(),c=X.agents(e)[0],before=e.state.playerFamily.spiritStones;const multiplier=e.cultivation.multiplier(c);X.action(e,'commission:herbs',c.id);assert.equal(e.state.playerFamily.spiritStones,before-40);assert.equal(X.busy(e.state,c.id),true);assert.equal(e.cultivation.multiplier(c),multiplier*.75);const herbs=e.state.alpha.herbs;advance(e,2);assert.equal(e.state.expansion.jobs.length,1);advance(e,1);assert.equal(e.state.expansion.jobs.length,0);assert.equal(e.state.alpha.herbs,herbs+42);assert.equal(e.state.expansion.completedJobs,1);assert.equal(e.saves.load().expansion.completedJobs,1);});
test('不能重复派遣，不能超出委托槽位',()=>{const e=game(),c=X.agents(e);X.action(e,'commission:herbs',c[0].id);const stones=e.state.playerFamily.spiritStones;assert.match(X.action(e,'commission:ore',c[0].id),/空闲/);assert.equal(e.state.playerFamily.spiritStones,stones);X.action(e,'commission:herbs',c[1].id);assert.match(X.action(e,'commission:herbs',c[2].id),/槽位/);assert.equal(e.state.expansion.jobs.length,2);});
test('委托人员不能参与远征',()=>{const e=game(),c=X.agents(e);X.action(e,'commission:herbs',c[0].id);assert.equal(e.world.startExpedition('black_water_ridge',c.slice(0,3).map(c=>c.id)),false);});
test('资源不足的操作不扣资源、不发委托',()=>{const e=game();e.state.playerFamily.spiritStones=0;assert.match(X.action(e,'commission:ore',X.agents(e)[0].id),/灵石不足/);assert.equal(e.state.expansion.jobs.length,0);assert.match(X.action(e,'study:breath'),/不足/);assert.equal(e.state.expansion.research,null);});
test('研习前置、互斥、时间与真实修炼加成',()=>{const e=game(),c=e.world.residents().find(c=>c.cultivationStarted),before=e.cultivation.multiplier(c);assert.match(X.action(e,'study:meridian'),/前置/);X.action(e,'study:breath');assert.match(X.action(e,'study:herbal'),/正在研习/);advance(e,5);assert.equal(e.state.expansion.studies.length,0);advance(e,1);assert.deepEqual(e.state.expansion.studies,['breath']);assert.ok(Math.abs(e.cultivation.multiplier(c)/before-1.08)<1e-6);assert.equal(e.state.expansion.research,null);});
test('议事不会重复领取，也不会积压',()=>{const e=game(),before=e.state.alpha.herbs;X.action(e,'season:1');assert.equal(e.state.alpha.herbs,before+12);X.action(e,'season:1');assert.equal(e.state.alpha.herbs,before+12);advance(e,3);assert.equal(e.state.expansion.seasonEvent.index,1);advance(e,6);assert.equal(e.state.expansion.seasonEvent.index,1);});
test('目标奖励只领取一次',()=>{const e=game();X.action(e,'commission:herbs',X.agents(e)[0].id);advance(e,3);const stones=e.state.playerFamily.spiritStones;X.action(e,'claim:first_job');assert.equal(e.state.playerFamily.spiritStones,stones+100);X.action(e,'claim:first_job');assert.equal(e.state.playerFamily.spiritStones,stones+100);});
test('灵植研习每年兑现额外产出',()=>{const e=game('production'),s=e.state;s.alpha.herbs=100;X.action(e,'study:herbal');advance(e,6);const herbs=s.alpha.herbs;advance(e,6);assert.equal(s.alpha.herbs,herbs+24+36);W.validateState(s);});
test('JSON和压缩存档保留在途委托及研习',()=>{const e=game();X.action(e,'commission:herbs',X.agents(e)[0].id);X.action(e,'study:breath');e.save();const s=e.saves.load();assert.equal(s.expansion.jobs.length,1);assert.equal(s.expansion.research.id,'breath');X.validate(s);W.validateState(s);const reload=new W.Engine(s,e.saves);X.attach(reload);advance(reload,6);assert.equal(reload.state.expansion.completedJobs,1);assert.ok(reload.state.expansion.studies.includes('breath'));});
test('损坏经营存档会被拒绝',()=>{const e=game();e.state.expansion.jobs=[{id:'x',type:'herbs',agent:'missing',started:0,ends:3}];assert.throws(()=>X.validate(e.state),/委托/);});
test('五年模拟保持原有存档约束',()=>{const e=game('long-running');X.action(e,'study:breath');X.action(e,'commission:herbs',X.agents(e)[0].id);advance(e,60);W.validateState(e.state);X.validate(e.state);assert.equal(e.state.meta.gameYear,6);});
console.log(passed+' simulation checks passed.');
