const assert=require('node:assert/strict');
const W=require('../core.js'),F=require('../frontier.js'),X=require('../expansion.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
function game(){const saves=new W.SaveSystem(new W.MemoryStorage()),e=W.Engine.create('陈','frontier-qa',0,Date.now(),saves);X.attach(e);F.attach(e);e.start();e.marriage.tick=()=>{};e.world.events.annual=()=>{};return e;}
function cultivator(e,realm='nascent'){const c=e.world.residents().find(c=>c.cultivationStarted);Object.assign(c,{realm,realmStage:4,baseLifespan:W.CONFIG.lifespan[realm],cultivationProgress:1,isBottleneck:true,health:'healthy',retryAtMonth:0});return c;}
function advance(e,n){for(let i=0;i<n;i++){e.state.pendingDecisions=[];e.time.tick();}}
test('丹药、材料交易真实扣费入库',()=>{const e=game(),s=e.state;F.action(e,'shopbuy:herbBundle:1');assert.equal(s.alpha.herbs,60);assert.equal(s.playerFamily.spiritStones,990);F.action(e,'shopbuy:crystal:1');assert.equal(s.alpha.materials,30);assert.equal(s.playerFamily.spiritStones,690);F.validate(s);});
test('库存不足、灵石不足、非法数量不会扣费',()=>{const e=game(),s=e.state;const before=s.playerFamily.spiritStones;assert.match(F.action(e,'shopbuy:healing:99'),/无效/);s.frontier.stocks.healing=0;assert.match(F.action(e,'shopbuy:healing:1'),/库存/);assert.equal(s.playerFamily.spiritStones,before);s.playerFamily.spiritStones=0;assert.match(F.action(e,'shopbuy:crystal:1'),/不足/);});
test('材料出售有数量校验和实际灵石收益',()=>{const e=game();e.state.alpha.herbs=50;F.action(e,'shopsell:herbs:10');assert.equal(e.state.alpha.herbs,40);assert.equal(e.state.playerFamily.spiritStones,1230);const before=e.state.playerFamily.spiritStones;F.action(e,'shopsell:herbs:50');assert.equal(e.state.playerFamily.spiritStones,before);});
test('疗伤露缩短伤期，健康或濒危人物不消耗',()=>{const e=game(),c=e.world.residents()[0];e.state.frontier.bag.healing=2;Object.assign(c,{health:'light',injuryMonths:4});F.action(e,'baguse:healing',c.id);assert.equal(c.health,'healthy');assert.equal(c.injuryMonths,0);assert.equal(F.inventory(e,'healing'),1);F.action(e,'baguse:healing',c.id);assert.equal(F.inventory(e,'healing'),1);c.health='critical';c.injuryMonths=20;F.action(e,'baguse:healing',c.id);assert.equal(F.inventory(e,'healing'),1);});
test('残卷悟性永久加成与五卷上限',()=>{const e=game(),c=e.world.residents()[0],initial=c.comprehension;e.state.frontier.bag.manual=6;for(let i=0;i<6;i++)F.action(e,'baguse:manual',c.id);assert.equal(c.comprehension,Math.min(100,initial+10));assert.equal(F.inventory(e,'manual'),1);assert.equal(e.state.frontier.manualUses[c.id],5);});
test('法器装备互换返还旧法器，聚灵珠影响修炼',()=>{const e=game(),c=cultivator(e,'qi'),f=e.state.frontier,base=e.cultivation.multiplier(c);f.bag.ring=1;f.bag.sword=1;F.action(e,'baguse:ring',c.id);assert.equal(f.equipment[c.id],'ring');assert.ok(Math.abs(e.cultivation.multiplier(c)-base*1.1)<1e-6);F.action(e,'baguse:sword',c.id);assert.equal(f.equipment[c.id],'sword');assert.equal(f.bag.ring,1);assert.equal(f.bag.sword,0);});
test('锦囊派遣一次消耗一次，收益实际增加',()=>{const e=game(),c=e.world.residents()[0];e.state.frontier.bag.supply=1;X.action(e,'commission:herbs',c.id);assert.equal(e.state.frontier.bag.supply,0);assert.equal(e.state.expansion.jobs[0].supplied,true);advance(e,3);assert.equal(e.state.alpha.herbs,Math.round(42*1.2));});
test('真实六境配置、寿元、突破目标',()=>{const e=game(),c=cultivator(e);assert.equal(e.cultivation.target(c),'spirit');c.realm='spirit';assert.equal(e.cultivation.target(c),'void');assert.equal(W.label('spirit'),'化神');assert.equal(W.label('void'),'炼虚');assert.equal(W.CONFIG.lifespan.void,4800);assert.equal(W.ALPHA_CONFIG.familyRanks[6].capacity,900);});
test('玄天界门需要元婴修士及资源',()=>{const e=game();e.state.playerFamily.spiritStones=6000;e.state.alpha.materials=300;assert.match(F.action(e,'frontier_open'),/元婴/);cultivator(e);F.action(e,'frontier_open');assert.equal(e.state.frontier.unlocked,true);assert.equal(e.state.playerFamily.spiritStones,1000);assert.equal(e.state.alpha.materials,100);});
test('化神突破环境严格校验，服丹消耗一次',()=>{const e=game(),c=cultivator(e),s=e.state;s.playerFamily.rank=4;s.playerFamily.spiritStones=200000;s.alpha.herbs=30000;s.alpha.materials=15000;s.frontier.bag.spiritPill=1;assert.equal(e.cultivation.resourcesReady(c),false);s.frontier.unlocked=true;s.alpha.buildings.spiritVein=4;s.alpha.buildings.library=4;s.playerFamily.spiritVeinTier='3';assert.equal(e.cultivation.resourcesReady(c),true);const chance=e.cultivation.chance(c);e.rng.chance=p=>{assert.ok(Math.abs(p-Math.min(W.CONFIG.majorMax,chance+.12))<1e-6);return true;};assert.equal(e.cultivation.attempt(c,true),true);assert.equal(c.realm,'spirit');assert.equal(c.baseLifespan,2200);assert.equal(s.frontier.bag.spiritPill,0);assert.equal(s.playerFamily.spiritStones,80000);W.validateState(s);F.validate(s);});
test('炼虚突破真实消耗与保存加载',()=>{const e=game(),c=cultivator(e,'spirit'),s=e.state;s.playerFamily.rank=5;s.playerFamily.spiritStones=500000;s.alpha.herbs=40000;s.alpha.materials=20000;s.alpha.buildings.spiritVein=5;s.alpha.buildings.library=5;s.playerFamily.spiritVeinTier='4';s.frontier.unlocked=true;e.rng.chance=()=>true;assert.equal(e.cultivation.attempt(c),true);assert.equal(c.realm,'void');assert.equal(s.playerFamily.spiritStones,140000);assert.equal(c.baseLifespan,4800);e.save();const loaded=e.saves.load();assert.equal(loaded.characters.alive[c.id].realm,'void');F.validate(loaded);});
test('炼虚圆满为终境，不出现第五小境界',()=>{const e=game(),c=cultivator(e,'void');e.cultivation.tick([c]);assert.equal(c.realmStage,4);assert.equal(e.cultivation.target(c),null);W.validateState(e.state);});
test('六级建筑可升级，不越星级，不越上限',()=>{const e=game(),s=e.state;s.playerFamily.rank=5;s.playerFamily.spiritStones=1000000;s.alpha.buildings.library=4;assert.equal(e.world.upgrade('library'),true);assert.equal(s.alpha.buildings.library,5);assert.equal(e.world.upgrade('library'),false);s.playerFamily.rank=6;assert.equal(e.world.upgrade('library'),true);assert.equal(e.world.upgrade('library'),false);W.validateState(s);});
test('玄天远行按时结算，珍材入库且人手互斥',()=>{const e=game(),c=cultivator(e),s=e.state;s.frontier.unlocked=true;s.playerFamily.spiritStones=5000;c.isBottleneck=false;c.cultivationProgress=0;F.action(e,'journey:garden',c.id);assert.equal(s.frontier.journeys.length,1);assert.equal(X.busy(s,c.id),true);assert.match(X.action(e,'commission:herbs',c.id),/空闲/);advance(e,6);assert.equal(s.frontier.journeys.length,0);assert.equal(s.frontier.completed,1);assert.ok(s.frontier.bag.lotus>=1);assert.ok(s.alpha.herbs>=1020);});
test('高阶丹药配方有珍材成本且不能重复免费领取',()=>{const e=game();cultivator(e);const s=e.state;s.frontier.unlocked=true;s.frontier.bag.lotus=2;s.alpha.herbs=800;s.alpha.materials=300;s.playerFamily.spiritStones=2000;F.action(e,'alchemy:spiritPill');assert.equal(s.frontier.bag.spiritPill,1);assert.equal(s.frontier.bag.lotus,0);assert.equal(s.playerFamily.spiritStones,0);F.action(e,'alchemy:spiritPill');assert.equal(s.frontier.bag.spiritPill,1);});
test('通知永久等待确认，后台和月份推进受阻',()=>{const q=new W.PresentationQueue();q.push({key:'a',title:'通知',body:'test',kind:'card'});q.update(600);assert.equal(q.active.key,'a');assert.equal(q.paused,true);q.dismiss();assert.equal(q.paused,false);const e=game();e.pauseGuard=()=>true;const before=W.absoluteMonth(e.state);e.time.tick();assert.equal(W.absoluteMonth(e.state),before);});
test('未处理抉择会中断时间与离线推进，保留离线余额',()=>{const e=game(),s=e.state,c=e.world.residents()[0];s.pendingDecisions=[{id:'test_decision',type:'major_breakthrough',characterId:c.id,createdGameYear:1,payload:{target:'foundation'}}];const before=W.absoluteMonth(s);e.time.tick();assert.equal(W.absoluteMonth(s),before);const report=e.time.offline(s.meta.lastExitAt+3600000);assert.equal(report.months,0);assert.ok(s.meta.offlineCarryMs>=3600000);});
test('旧存档初始化、装备及玄天行程往返与损坏拒绝',()=>{const e=game(),s=e.state;s.frontier.bag.manual=2;e.save();const loaded=e.saves.load();assert.equal(loaded.frontier.bag.manual,2);F.validate(loaded);loaded.frontier.bag.manual=-1;assert.throws(()=>F.validate(loaded),/数量/);});
test('1.2.2旧档迁移到1.3.0并保留族人及原传承',()=>{const e=game(),raw=JSON.parse(JSON.stringify(e.state));raw.meta.saveVersion='1.2.2';delete raw.frontier;raw.expansion.studies=['breath'];const migrated=e.saves.migrate(raw);assert.equal(migrated.meta.saveVersion,'1.3.0');assert.ok(migrated.expansion.studies.includes('breath'));assert.equal(Object.keys(migrated.characters.alive).length,Object.keys(raw.characters.alive).length);const next=new W.Engine(migrated,e.saves);X.attach(next);F.attach(next);assert.equal(next.state.frontier.unlocked,false);});
test('装备可卸回族库；远行期间不能更换或卸下',()=>{const e=game(),c=cultivator(e,'qi'),f=e.state.frontier;f.bag.sword=1;f.bag.ring=1;F.action(e,'baguse:sword',c.id);X.action(e,'commission:herbs',c.id);assert.match(F.action(e,'bagunequip:'+c.id),/远行/);assert.match(F.action(e,'baguse:ring',c.id),/远行/);advance(e,3);F.action(e,'bagunequip:'+c.id);assert.equal(f.equipment[c.id],undefined);assert.equal(f.bag.sword,1);});
test('材料买入后卖出不能形成无风险套利',()=>{const e=game(),before=e.state.playerFamily.spiritStones;F.action(e,'shopbuy:crystal:1');F.action(e,'shopsell:materials:10');F.action(e,'shopsell:materials:10');F.action(e,'shopsell:materials:10');assert.ok(e.state.playerFamily.spiritStones<before);});
test('晋阶条件变化时可明确暂缓，避免被锁在窗口',()=>{const e=game(),s=e.state;s.pendingDecisions=[{id:'rank_test',type:'rank',characterId:null,createdGameYear:1,payload:{target:2}}];assert.equal(e.world.rankEligible(),false);assert.match(F.action(e,'postpone:rank_test'),/已暂缓/);assert.equal(s.pendingDecisions.length,0);e.time.tick();assert.equal(s.meta.gameMonth,2);});
test('事件延期保留原抉择及上下文，十二月后重新请示',()=>{const e=game(),c=e.world.residents()[0],template=e.world.events.templates.find(t=>t.choices.length&&t.category==='family')||e.world.events.templates.find(t=>t.choices.length);e.world.events.fire(template.id,{actorId:c.id,factionId:e.state.alpha.world[0].id},true);const d=e.state.pendingDecisions.find(d=>d.type==='event');assert.ok(d);const copy=JSON.parse(JSON.stringify(d));F.action(e,'postpone:'+d.id);assert.equal(e.state.pendingDecisions.length,0);assert.equal(e.state.frontier.postponed.length,1);advance(e,12);assert.deepEqual(e.state.pendingDecisions.find(x=>x.id===copy.id),copy);assert.equal(e.state.frontier.postponed.length,0);});
console.log(count+' frontier checks passed.');
